import {
	Activity,
	AlertCircle,
	AlertTriangle,
	Archive,
	ArrowRightCircle,
	ArrowLeft,
	ArrowUpRight,
	BarChart,
	Briefcase,
	Calendar,
	CheckCircle,
	Check,
	ChevronRight,
	ChevronsRight,
	Clock,
	Copy,
	Delete,
	Download,
	Pen,
	EditSquare,
	Edit,
	ExternalLink,
	EyeOff,
	Eye,
	FileMinus,
	FilePlus,
	File,
	Filter,
	FolderMinus,
	FolderPlus,
	Folder,
	HeartFill,
	Heart,
	HelpCircle,
	Home,
	InfoCircle,
	LinkHorizontal,
	Link,
	List,
	Lock,
	LogIn,
	LogOut,
	Logo,
	Mail,
	Maximize,
	Menu,
	MessageSquare,
	Minimize,
	MinusCircle,
	Minus,
	Moon,
	MoreHorizontal,
	PieChart,
	PlusCircle,
	Plus,
	Pause,
	Play,
	Power,
	Search,
	Send,
	Settings,
	Share,
	Slash,
	SortAsc,
	SortDesc,
	StarFill,
	Star,
	Sun,
	Tag,
	Target,
	Terminal,
	Trash,
	Unlock,
	Upload,
	User,
	UserCheck,
	UserMinus,
	UserPlus,
	UserX,
	Users,
	XCircle,
	X,
	Layers,
	ZoomIn,
	ZoomOut,
	Save,
} from "@assets/pictos";

export type TPictoName = keyof typeof Pictos;

export type TPictos = {
	[key in TPictoName]: string;
};

export const Pictos = {
	logo: Logo,
	activity: Activity,
	add: Plus,
	addCircle: PlusCircle,
	alert: AlertCircle,
	alertTriangle: AlertTriangle,
	archive: Archive,
	arrow: ArrowLeft,
	arrowCircle: ArrowRightCircle,
	arrowUpRight: ArrowUpRight,
	barChart: BarChart,
	briefcase: Briefcase,
	calendar: Calendar,
	check: Check,
	checkCircle: CheckCircle,
	chevron: ChevronRight,
	chevrons: ChevronsRight,
	clock: Clock,
	copy: Copy,
	cross: X,
	crossCircle: XCircle,
	delete: Delete,
	download: Download,
	edit: Edit,
	editSquare: EditSquare,
	externalLink: ExternalLink,
	eye: Eye,
	eyeOff: EyeOff,
	file: File,
	fileMinus: FileMinus,
	filePlus: FilePlus,
	filter: Filter,
	folder: Folder,
	folderMinus: FolderMinus,
	folderPlus: FolderPlus,
	heart: Heart,
	heartFill: HeartFill,
	help: HelpCircle,
	home: Home,
	info: InfoCircle,
	layers: Layers,
	link: Link,
	linkH: LinkHorizontal,
	list: List,
	lock: Lock,
	login: LogIn,
	logout: LogOut,
	mail: Mail,
	maximize: Maximize,
	menu: Menu,
	messageSquare: MessageSquare,
	minimize: Minimize,
	minus: Minus,
	minusCircle: MinusCircle,
	moon: Moon,
	more: MoreHorizontal,
	pause: Pause,
	play: Play,
	pen: Pen,
	pieChart: PieChart,
	power: Power,
	save: Save,
	search: Search,
	send: Send,
	settings: Settings,
	share: Share,
	slash: Slash,
	sortAsc: SortAsc,
	sortDesc: SortDesc,
	star: Star,
	starFill: StarFill,
	sun: Sun,
	tag: Tag,
	target: Target,
	terminal: Terminal,
	trash: Trash,
	unlock: Unlock,
	upload: Upload,
	user: User,
	userCheck: UserCheck,
	userMinus: UserMinus,
	userPlus: UserPlus,
	userX: UserX,
	users: Users,
	zoomIn: ZoomIn,
	zoomOut: ZoomOut,
};
